#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DB_MIGRATOR_USER} WITH PASSWORD '${DB_MIGRATOR_PASSWORD}';
    CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';

    CREATE DATABASE ${DB_NAME} OWNER ${DB_MIGRATOR_USER};

    \c ${DB_NAME}

    GRANT USAGE ON SCHEMA public TO ${DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER} IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_MIGRATOR_USER} IN SCHEMA public
      GRANT USAGE, SELECT ON SEQUENCES TO ${DB_USER};
EOSQL