services:
  lms:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - lms-network
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: lms-postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_MIGRATOR_USER: ${DB_MIGRATOR_USER}
      DB_MIGRATOR_PASSWORD: ${DB_MIGRATOR_PASSWORD}
    depends_on:
      lms-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  lms-postgres:
    image: postgres:17-alpine
    container_name: lms-postgres
    restart: unless-stopped
    networks:
      - lms-network
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MIGRATOR_USER: ${DB_MIGRATOR_USER}
      DB_MIGRATOR_PASSWORD: ${DB_MIGRATOR_PASSWORD}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    ports:
      - "127.0.0.1:${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  postgres_data:
    name: postgres_data_lms

networks:
  lms-network:
    name: lms-network
    driver: bridge